ALL:
	gcc -c launch.c -Wall -Wextra 
	gcc -o launch launch.o -lm 
	gcc -c tube.c -Wall -Wextra 
	gcc -o tube tube.o -lm
LAUNCH:
	gcc -c launch.c -Wall -Wextra 
	gcc -o launch launch.o -lm 	
TUBE:
	gcc -c tube.c -Wall -Wextra 
	gcc -o tube tube.o -lm
CLEAN:
	rm launch launch.o
	rm tube tube.o